### ISSUE TITLE
Prerequisite relationship

### ISSUE THREAD

**Issue by abensaid** [CurricularAnalytics/CA-Notebooks#4]
Hi
Thank you for the interesting work and helpfull and clear implementation.
I have a quesiton related to the curriculum graph.
Assume we have the following:
![image](https://user-images.githubusercontent.com/17796956/147869144-5293d49d-2e8d-43c8-984a-9d2501500868.png)

Does this mean a student needs to fullfill both v1 and v2 to enroll for v3? or a student needs to fullfill either v1 or v2 to enroll for v3?
Thank you.

**Comment by heileman** [comment]
The assumption is that the student needs to complete both v1 and v2 before attempting v3, i.e., the assumption is a logical AND operation. For the purpose of computing the complexity of a curriculum, logical OR relationships are irrelevant, i.e., they don't change the complexity of the curriculum.

**Comment by abensaid** [comment]
Thank you for the clarification.
